syntax = "proto3";
package com.example.proto;
option java_package = "com.example.proto.generated";
option java_outer_classname = "MediaplayerOuterClass";

message MediaItem {
  string id = 1;
  string title = 2;
  
  oneof content {
    Video video = 3;
    Audio audio = 4;
    Image image = 5;
  }

  message Video {
    int32 duration_seconds = 1;
    string codec = 2;
    Resolution resolution = 3;
  }

  message Audio {
    int32 duration_seconds = 1;
    int32 bitrate = 2;
  }

  message Image {
    int32 width = 1;
    int32 height = 2;
    string format = 3;
  }

  message Resolution {
    int32 width = 1;
    int32 height = 2;
  }
}
